// cannot use both meta data and generateMetadata at once

import { Metadata } from "next"

// cannot be used with client components
export const metadata: Metadata = {
  title: {
    default: 'Default title', // a fallback title when children does not have there own metadata
    template: 'Suffix %s Product layout', // to add suffix or prefix to child title %s take the child title
    absolute: "" // to override parent metadata title
  },
  description: 'Generated by Next.js',
}

export default function ProductLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header style={{
        backgroundColor: "lightskyblue",
        padding: "1rem"
      }}>
        <p>
          Products layout
        </p>
      </header>
      <body>{children}</body>
      <footer style={{
        backgroundColor: "ghostWhite",
        padding: "1rem"
      }}>
        <p>
          Footer
        </p>
      </footer>
    </html>
  )
}
