export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header style={{
        backgroundColor: "red",
        padding: "1rem"
      }}>
        <p>
          Auth layout
        </p>
      </header>
      <body>{children}</body>
      <footer style={{
        backgroundColor: "ghostWhite",
        padding: "1rem"
      }}>
        <p>
          Footer
        </p>
      </footer>
    </html>
  )
}
