"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { useState } from "react"

// not possible with client component
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const navLinks = [
  { name: "Register", href: "/register" },
  { name: "Login", href: "/login" },
  { name: "Forgot password", href: "/forgot-password" }
]

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [authState, setAuthState] = useState("")// UI state does not re-renders for each page change
  const pathName = usePathname() // to style active link component

  return (
    <html lang="en">
      <header style={{
        backgroundColor: "red",
        padding: "1rem"
      }}>
        <p>
          Auth layout {authState}
        </p>
        <p>
          Pathname {pathName}
        </p>
      </header>
      <body>
        <label htmlFor="template">Template</label>
        <input id="template" type="text" onChange={(e) => setAuthState(e.target.value)} />
        <div>
          {navLinks?.map((link) => (
            <Link key={`link-${link.name}`} href={link.href}>{link.name}</Link>
          ))}
        </div>
        {children}
      </body>
      <footer style={{
        backgroundColor: "ghostWhite",
        padding: "1rem"
      }}>
        <p>
          Footer
        </p>
      </footer>
    </html>
  )
}
